seq="TGATATACGTACACCACAATGCTGGTGGCGAAGCATGGGAAAGACATCGGCACAACCATAAAGCTTGTCGAATACGTGACGTGCAATACCTTCTTACAGCTTAATGGGAAGTAGAGGTCAGCCATCCTCGCTTGGTTCGTGACCGATTAAATGTCCCCCGCCAAGCCGGTATCAAAGTGCCGAGAGACATTCGTACTACCTAGACTTAGACTAGAACCCCTTCTGTCCAAAACCACTTTGCCCGCCACTTTATATCTCACGAACCGACTTGACGGTTCGACCGTTGCATTTCGTACGCGAAAAGTCGCCCACTGAAGTCCAGCGGCTTGGTCCGCACAACCGGCGTGACCCTGCTATTAGTGATATTCATTGTTAAATAAGAAAGAGAACATGGGGAGTCCTCACATTCCCGCGCGTTGCTCGACGTAAGATGCACCCCGTACATACCCTCCTAACCGCTTGGAATGTTGCTTCTACACCAAGTATAACCGCATGGACTCAAACTTTTAACTGAGTATCGCAGGTGTCGGTGGCTAAATGGCACGGGTGCGCTCTAGAGAGTCTACTGTGTCCTCGGCCGCATATGATGTGGCTCGGTGAGACCAGCTGTCGCAGAATATGGAGCTTTGCCAATGAGTTTAAATCGTTTACGCGTATGAGCTTTAAACGTACTAGCCAACTTTTAACTTCTCCTGCCATGAGACCCATATTCTTAAGGACACCTCCCTATGTTTTCAGCTCCAAGATATGATGAGCAGCGCTTGTCAGCACTAGCGGGGAGTTGTCATCTAGTGCTCCTTCGATTAGCGCGGCCCCGCTCAGCGGACCACTAACAACGCCAGTTTGAATGACCTACCCCACCACCTATTCCGTAGTCGACTTAGACATGATGCTTCATCTAACCCCAACCAACGTGGTTTGCTTTTTCAGCTGCCAGCGGGCACTGTTGTACATTAC"

rev_seq=""
a=seq[::-1]

for s in a:
    if s == "C":
        rev_seq += "G"
    if s == "G":
        rev_seq += "C"
    if s == "A":
        rev_seq += "T"
    if s == "T":
        rev_seq += "A"

print(rev_seq)
